name: Check Branch Lock Status

on:
  pull_request:
    branches:
      - 'develop/subscriptions'
    types: [opened,edited,reopened,synchronize,labeled,unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Allow sync PRs to merge.
        if: ${{ github.event.pull_request.user.login == 'cb-mohitbhatia' }}
        run: |
          echo "Distributed GitFlow Bot PR. Workflow will pass."
          exit 0

      - name: Checkout code
        uses: actions/checkout@v2
