name: Check Branch Lock Status

on:
  pull_request:
    branches:
      - 'develop/subscriptions'
    types: [opened,edited,reopened,synchronize,labeled,unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.pull_request.user.login != 'ddd' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get branch name
        id: branch_name
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."

